approved_urls = {'https://pro-api.coinmarketcap.com': True}
CMC_PROD_ENDPOINT = 'https://pro-api.coinmarketcap.com'
JSON_HEADER = {'Accepts': 'application/json'}
LATEST_TOKENS_CMC = '/v1/cryptocurrency/listings/latest'
LATEST_QUOTES_CMC = '/v2/cryptocurrency/quotes/latest'
CRYPTO_META_DATA_CMC = '/v2/cryptocurrency/info'
CRYPTO_WATCH_LIST = 'evmos,bitcoin,ethereum,cosmos,juno,brave'
CHOICE_CURRENCY = 'USD'
SLUG = 'slug'
CONVERT = 'convert'
